# Generated by Django 3.1.2 on 2020-10-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='series_id',
            new_name='series',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='category_id',
            new_name='category',
        ),
    ]
