# Generated by Django 3.1.1 on 2020-10-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_1',
            new_name='address_first',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_2',
            new_name='address_second',
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
